%-----------------------------------------------------------------------
% Job saved on 11-Jul-2025 15:44:32 by cfg_util (rev $Rev: 8183 $)
% spm SPM - SPM25 (25.01.02)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.fmri_spec.dir = {'/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/glm'};
matlabbatch{1}.spm.stats.fmri_spec.timing.units = 'scans';
matlabbatch{1}.spm.stats.fmri_spec.timing.RT = 2;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t = 16;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t0 = 8;
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.scans = {
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0000.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0001.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0002.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0003.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0004.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0005.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0006.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0007.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0008.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0009.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0010.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0011.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0012.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0013.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0014.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0015.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0016.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0017.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0018.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0019.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0020.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0021.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0022.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0023.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0024.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0025.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0026.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0027.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0028.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0029.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0030.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0031.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0032.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0033.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0034.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0035.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0036.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0037.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0038.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0039.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0040.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0041.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0042.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0043.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0044.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0045.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0046.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0047.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0048.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0049.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0050.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0051.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0052.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0053.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0054.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0055.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0056.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0057.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0058.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0059.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0060.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0061.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0062.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0063.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0064.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0065.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0066.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0067.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0068.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0069.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0070.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0071.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0072.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0073.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0074.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0075.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0076.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0077.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0078.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0079.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0080.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0081.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0082.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0083.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0084.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0085.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0086.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0087.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0088.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0089.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0090.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0091.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0092.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0093.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0094.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0095.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0096.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0097.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0098.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0099.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0100.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0101.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0102.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0103.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0104.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0105.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0106.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0107.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0108.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0109.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0110.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0111.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0112.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0113.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0114.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0115.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0116.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0117.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0118.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0119.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0120.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0121.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0122.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0123.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0124.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0125.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0126.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0127.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0128.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0129.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0130.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0131.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0132.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0133.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0134.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0135.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0136.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0137.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0138.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0139.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0140.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0141.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0142.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0143.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0144.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0145.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0146.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0147.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0148.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0149.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0150.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0151.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0152.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0153.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0154.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0155.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0156.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0157.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0158.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0159.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0160.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0161.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0162.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0163.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0164.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0165.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0166.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0167.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0168.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0169.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0170.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0171.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0172.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0173.img,1'
                                                 '/Users/abhijitc/Documents/Abhijit/LenaLab_DCM/spDCM/func/swrest0174.img,1'
                                                 };
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.cond = struct('name', {}, 'onset', {}, 'duration', {}, 'tmod', {}, 'pmod', {}, 'orth', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi = {''};
matlabbatch{1}.spm.stats.fmri_spec.sess.regress = struct('name', {}, 'val', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi_reg = {''};
matlabbatch{1}.spm.stats.fmri_spec.sess.hpf = 128;
matlabbatch{1}.spm.stats.fmri_spec.fact = struct('name', {}, 'levels', {});
matlabbatch{1}.spm.stats.fmri_spec.bases.hrf.derivs = [0 0];
matlabbatch{1}.spm.stats.fmri_spec.volt = 1;
matlabbatch{1}.spm.stats.fmri_spec.global = 'None';
matlabbatch{1}.spm.stats.fmri_spec.mthresh = 0.8;
matlabbatch{1}.spm.stats.fmri_spec.mask = {''};
matlabbatch{1}.spm.stats.fmri_spec.cvi = 'AR(1)';
